Loading rhel8/default-amp
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 libpciaccess/0.16/gcc-9.4.0-6fonbj6
    libiconv/1.16/gcc-9.4.0-ahebbov libxml2/2.9.12/gcc-9.4.0-gnknt5e
    ncurses/6.2/gcc-9.4.0-aiirok7 hwloc/2.5.0/gcc-9.4.0-7sqomga
    libevent/2.1.12/gcc-9.4.0-hgny7cm numactl/2.0.14/gcc-9.4.0-52dwc6n
    cuda/11.4.0/gcc-9.4.0-3hnxhjt gdrcopy/2.2/gcc-9.4.0-e4igtfp
    knem/1.1.4/gcc-9.4.0-bpbxgva libnl/3.3.0/gcc-9.4.0-whwhrwb
    rdma-core/34.0/gcc-9.4.0-5eo5n2u ucx/1.11.1/gcc-9.4.0-lktqyl4
    openmpi/4.1.1/gcc-9.4.0-epagguv
Changed directory to /rds/user/ejg84/hpc-work/MLMI2/exp.

JobID: 36979305
======
Time: Sat  9 Dec 10:02:54 GMT 2023
Running on master node: gpu-q-58
Current directory: /rds/user/ejg84/hpc-work/MLMI2/exp
/var/spool/slurm/slurmd/job36979305/slurm_script: line 104: machine_files/machine.file.36979305: No such file or directory

Nodes allocated:
================
cat: machine_files/machine.file.36979305: No such file or directory


numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
python -u run.py --is_bidir > logs/out.36979305

Traceback (most recent call last):
  File "/rds/user/ejg84/hpc-work/MLMI2/exp/run.py", line 69, in <module>
    model_path = train(model, args)
  File "/rds/user/ejg84/hpc-work/MLMI2/exp/trainer.py", line 74, in train
    avg_train_loss = train_one_epoch(epoch)
  File "/rds/user/ejg84/hpc-work/MLMI2/exp/trainer.py", line 45, in train_one_epoch
    outputs = log_softmax(model(inputs), dim=-1)
  File "/rds/project/rds-xyBFuSj0hm0/MLMI2.M2022/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/user/ejg84/hpc-work/MLMI2/exp/models.py", line 16, in forward
    output = self.proj(hidden)
  File "/rds/project/rds-xyBFuSj0hm0/MLMI2.M2022/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/project/rds-xyBFuSj0hm0/MLMI2.M2022/miniconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1936x128 and 256x40)
